<option value="VC_Nombre_Experiencia">Nombre experiencia</option>
<option value="TX_Tema">Temas</option>
<option value="TX_Materias">Materias</option>
<option value="TX_Intencion_Artistica">Intencion artistica</option>
<option value="TX_Referentes">Referentes</option>
<option value="TX_Aplicabilidad_Referentes">Aplicabilidades</option>
<option value="TX_Ambientacion">Ambientacion</option>
<option value="TX_Dispositivos">Dispositivos</option>
<option value="TX_Momentos">Momentos</option>
<option value="TX_Ninos_Ins">Hallazgos entorno institucional: Niños/niñas</option>
<option value="TX_Agentes_Ins">Hallazgos entorno institucional: Agentes educativos</option>
<option value="TX_Ninos_Fam">Hallazgos entorno familiar: Niños/niñas</option>
<option value="TX_Agentes_Fam">Hallazgos entorno familiar: Agentes educativos</option>
<option value="TX_Familias_Fam">Hallazgos entorno familiar: Familias</option>
<option value="TX_Mujeres_Fam">Hallazgos entorno familiar: Mujeres gestantes</option>
<option value="TX_Ninos_Com">Hallazgos comunidad: Niños/niñas</option>
<option value="TX_Familias_Com">Hallazgos comunidad: Familias</option>
<option value="TX_Aprendizajes_Creacion">Reflexiones de los artistas: Desde la creación</option>
<option value="TX_Aprendizajes_Personales">Reflexiones de los artistas: Aprendizajes personales</option>
<option value="TX_Otros_Aspectos">Reflexiones de los artistas: Otros aspectos</option>