<option value="1">Sala Materna</option>
<option value="2">Caminadores</option>
<option value="3">Parvulos</option>
<option value="4">Prejardin</option>
<option value="5">Jardin</option>
<option value="6">Transicion</option>
<option value="7">Comunidad</option>
<option value="8">Entorno Familiar</option>
<option value="9">Sala Materna 1</option>
<option value="10">Sala Materna 2</option>
<option value="11">Sala Materna 3</option>
<option value="12">Sala Materna 4</option>
<option value="13">Sala Materna 5</option>
<option value="14">Sala Materna 6</option>
<option value="15">Caminadores 1</option>
<option value="16">Caminadores 2</option>
<option value="17">Caminadores 3</option>
<option value="18">Caminadores 4</option>
<option value="19">Caminadores 5</option>
<option value="20">Caminadores 6</option>
<option value="21">Caminadores 7</option>
<option value="22">Caminadores 8</option>
<option value="23">Parvulos 1</option>
<option value="24">Parvulos 2</option>
<option value="25">Parvulos 3</option>
<option value="26">Parvulos 4</option>
<option value="27">Parvulos 5</option>
<option value="28">Parvulos 6</option>
<option value="29">Parvulos 7</option>
<option value="30">Parvulos 8</option>
<option value="31">Parvulos 9</option>
<option value="32">Parvulos 10</option>
<option value="33">Prejardin 1</option>
<option value="34">Prejardin 2</option>
<option value="35">Prejardin 3</option>
<option value="36">Prejardin 4</option>
<option value="37">Prejardin 5</option>
<option value="38">Prejardin 6</option>
<option value="39">Prejardin 7</option>
<option value="40">Prejardin 8</option>
<option value="41">Prejardin 9</option>
<option value="42">Prejardin 10</option>
<option value="43">Jardin 1 JM</option>
<option value="44">Jardin 2 JM</option>
<option value="45">Jardin 3 JM</option>
<option value="46">Jardin 4 JM</option>
<option value="47">Jardin 5 JM</option>
<option value="48">Jardin 6 JM</option>
<option value="49">Jardin 7 JM</option>
<option value="50">Jardin 8 JM</option>
<option value="51">Jardin 9 JM</option>
<option value="52">Jardin 1 JT</option>
<option value="53">Jardin 2 JT</option>
<option value="54">Jardin 3 JT</option>
<option value="55">Jardin 4 JT</option>
<option value="56">Jardin 5 JT</option>
<option value="57">Jardin 6 JT</option>
<option value="58">Jardin 7 JT</option>
<option value="59">Jardin 8 JT</option>
<option value="60">Jardin 9 JT</option>
<option value="61">Transicion 1 JM</option>
<option value="62">Transicion 2 JM</option>
<option value="63">Transicion 3 JM</option>
<option value="64">Transicion 4 JM</option>
<option value="65">Transicion 5 JM</option>
<option value="66">Transicion 6 JM</option>
<option value="67">Transicion 7 JM</option>
<option value="68">Transicion 8 JM</option>
<option value="69">Transicion 9 JM</option>
<option value="70">Transicion 1 JT</option>
<option value="71">Transicion 2 JT</option>
<option value="72">Transicion 3 JT</option>
<option value="73">Transicion 4 JT</option>
<option value="74">Transicion 5 JT</option>
<option value="75">Transicion 6 JT</option>
<option value="76">Transicion 7 JT</option>
<option value="77">Transicion 8 JT</option>
<option value="78">Transicion 9 JT</option>
<option value="79">Multinivel</option>